### PR TITLE
Rename the intermediate node to imx7s-warp

### PR DESCRIPTION
**Pull request by texierp**

### CODE REVIEW

**Comment by texierp** [comment]
Hi @WaRP7 

Let me know if is it possible to become a official maintainer on this repo ?

Thank you

PJ

**Comment by WaRP7** [comment]
Hi PJ,

Is there a way you can provide an email so we can communicate in private.

Best,

**Comment by texierp** [comment]
Hi,

This is my email : texier.pj2@gmail.com.

BR

Pj

**Comment by texierp** [comment]
Hi @WaRP7,

Just one point concerning this PR, Could you merge this ?

Thanks

PJ

**Comment by texierp** [comment]
Thanks :)

**Comment by texierp** [comment]
Hi @WaRP7,

 Is there any advance concerning my question (maintainer) ? 

BR

PJ

**Pull request merged**
